---
title: "Untitled"
output: pdf_document
date: "2024-02-20"
---

movie1 <- read.csv("/cloud/project/Activity 3/movie1.csv")
movie2 <- read.csv("/cloud/project/Activity 3/movie2.csv")
movie3 <- read.csv("/cloud/project/Activity 3/movie3.csv")
movie4 <- read.csv("/cloud/project/Activity 3/movie4.csv")
movie5 <- read.csv("/cloud/project/Activity 3/movie5.csv")
movie6 <- read.csv("/cloud/project/Activity 3/movie6.csv")
movie7 <- read.csv("/cloud/project/Activity 3/movie7.csv")
movie8 <- read.csv("/cloud/project/Activity 3/movie8.csv")
movie9 <- read.csv("/cloud/project/Activity 3/movie9.csv")
movie10 <- read.csv("/cloud/project/Activity 3/movie10.csv")

colnames(movie2) <- colnames(movie1)
colnames(movie3) <- colnames(movie1)
colnames(movie4) <- colnames(movie1)
colnames(movie5) <- colnames(movie1)
colnames(movie6) <- colnames(movie1)
colnames(movie7) <- colnames(movie1)
colnames(movie8) <- colnames(movie1)
colnames(movie9) <- colnames(movie1)
colnames(movie10) <- colnames(movie1)

merged_movies <- rbind(movie1,movie2,movie3,movie4,movie5,movie6,movie7,movie8,movie9,movie10)


write.csv(merged_movies, "Mergedmovies.csv", row.names = FALSE)

